### PR TITLE
Enable trailing space and indentation tests (yamllint)

### PR DESCRIPTION
**Pull request by wjdp**
Results here:
https://gist.github.com/wjdp/33a71b1ba32dfe8a0214a483d1570231

Much to fix

### CODE REVIEW

**Comment by nhyty** [comment]
Is it worth doing all these fixes in this branch @wjdp

**Comment by wjdp** [comment]
@nhyty Eh, maybe, maybe not

**Comment by nhyty** [comment]
Helpful as ever I see @wjdp

**Comment by wjdp** [comment]
This isn't worth time, AFAIK provides no benefit other than to calm my OCD

**Pull request closed without merging**
