### PR TITLE
Googling results

### LINKED ISSUE #968: More googling
https://books.google.co.uk/books?id=dT8IAQAAMAAJ&q=nottingham+university+drama+society&dq=nottingham+university+drama+society&hl=en&sa=X&ved=0ahUKEwjco7DbtI_XAhWeF8AKHTXhC5MQ6AEINTAC

### PR DESCRIPTION
**Pull request by samozzy**
Made a start on #831 
Will close #968

### CODE REVIEW

**Comment by nhyty** [comment]
Is it possible to have it as role than name for people as that is what every other show file is?

**Comment by nhyty** [comment]
other than that it looks great

**Comment by nhyty** [comment]
Out of interest, how did you decide years and characters for val deans shows?

**Comment by samozzy** [comment]
@nhyty Similarly as with Izbicki, rough estimates based on one show per term assuming that the blog post has them in chronological order.

**Pull request merged**
