### PR TITLE
Migrate from Google Fonts to self-hosted

### LINKED ISSUE #512: Bundle Google Fonts with build process
*Note: performance is pretty damn good already*

Most of our assets are fetched pretty damn quickly as they're same-origin over HTTP/2. Google fonts on the other hand (22, 31, 32) is pretty damn ugly on the waterfall.

Item 22 especially, as a blocking CSS resource, the whole page waits for 0.5 seconds (here on a fast connection). In comparison this is poor. See if we can fetch all these resources in the build step then serve from same origin.

image

### PR DESCRIPTION
**Pull request by wjdp**
**Will close #512** :capital_abcd: 

- Montserrat and Open Sans added to bower deps
- Both included in main.sass with font paths adjusted
- Style tweaks as GF Montserrat is not the same as everyone elses'

### CODE REVIEW

**Comment by davelab6** [comment]
How do you track updates to these fonts?

**Comment by wjdp** [comment]
They're spec'ed as bower packages locked to a specific version. [Gemnasium](https://gemnasium.com/newtheatre/history-project) keeps an eye on all our dependencies and will flag up if packages have new versions.

**Comment by davelab6** [comment]
Great to know :) Thanks! 

cc https://github.com/google/fonts/issues/222

**Comment by wjdp** [comment]
Prompted by your comment I'm reconsidering self-hosting (testing on live site currently). When self hosted the fonts seem to 'pop-in' ~700ms on a cached page load, whereas the Google hosted ones do not. I'm not sure of the root cause of this but shall investigate. @davelab6 I see you do much work in this area, any ideas?

**Comment by davelab6** [comment]
Its likely caching, but could be just the ultra optimizations that the GF team put into serving web fonts. 

The font file URLs on Google Fonts CDN are cached for a year, and are the same for all sites that use the GF API. So the first site your browser visits will suffer the cache miss and download the font, which is varied based on user agent string to be as small as possible for your platform, and after that all sites that use the GF API will get a cache hit on the font and load it instantly. The CSS is also cached, so only requested once per browser per day per API URL.

**Comment by wjdp** [comment]
Thanks for the comment. I'm aware of the caching used, and I think this is what I've tried to do here (both the font and CSS are cached for a long time, see #566 ) and with the inspector it's shown they're being loaded from the cache. However the 'pop-in' is present. I'm in the process of setting up a staging site to demonstrate/test the issue.

**Comment by wjdp** [comment]
Self hosted fonts version is live here https://nthp-fonts.newtheatre.org.uk, when navigating back and forth between pages the font noticeably pops in during page load.

**Comment by davelab6** [comment]
Yep, I see it!

**Pull request merged**
