### PR TITLE
Add 'Aristotle & Socrates' 

### PR DESCRIPTION
**Pull request by samozzy**
Bedlam version to come!
(new branch name)

### CODE REVIEW

**Review by BenWoodford76 — APPROVED** [review]
Looks good to me!

**Comment by BenWoodford76** [comment]
have we got the info for this Sam?

**Comment by BenWoodford76** [comment]
This is now being added within my 2022-2023 season branch so can be ignored then deleted once that branch is merged

**Comment by samozzy** [comment]
Closed via #1804

**Pull request closed without merging**
