### PR TITLE
[WIP] Venue links

### LINKED ISSUE #1113: Adding links to venue pages
Would be nice to be able to link to websites of external venues, certainly places in edinburgh and the minack

### PR DESCRIPTION
**Pull request by samozzy**
Add `link-list` functionality to venue pages for websites, social media, etc.
To close #1113 
To Do:

- [ ] Figure out why icons aren't displaying properly
- [x] Fix some Studio A venue entries for this season

### CODE REVIEW

**Comment by samozzy** [comment]
@wjdp - Do you know why using links on a person page renders with icons and this one doesn't? [Lauren Grant](https://raw.githubusercontent.com/newtheatre/history-project/7dff2d980decf535ff22cce090f8b11c152ba97d/_people/lauren_grant.md) doesn't have a type as listed but still renders with the [fa-link](https://history.newtheatre.org.uk/people/lauren_grant/).

**Comment by nhyty** [comment]
@davidtaylorhq, any chance you could look at this to fix it?

**Comment by davidtaylorhq** [comment]
What's wrong with it?

**Comment by nhyty** [comment]
See the broken icons on links....

**Comment by davidtaylorhq** [comment]
I think the icons should now be fixed, but the netlify build is failing with

```
12:16:12 AM: Preparing Git Reference pull/1155/head
12:16:17 AM: Failing build: Failed to prepare repo
12:16:17 AM: failed during stage 'preparing repo': exit status 1
```
I don't think that's caused by anything I've done... I will have another look tomorrow.

**Comment by davidtaylorhq** [comment]
Closed in favour of #1214

**Pull request closed without merging**
