### PR TITLE
Upgrade/lunr

### PR DESCRIPTION
**Pull request by wjdp**
They've jumped from 0.x to 2.x pretty quick and broken things.

- [ ] Work out what they've broken
- [ ] Fix those things

### CODE REVIEW

**Comment by nhyty** [comment]
Any news on this

**Comment by wjdp** [comment]
Nope!

Best thing I've found for doing these more complex stuff for HP is to dedicate a weekend every month or so to getting them done. This isn't something that can get done in an evening.

**Comment by BenWoodford76** [comment]
@samozzy fancy taking a look at this while you're on a roll?? :)

**Comment by wjdp** [comment]
Old

**Pull request closed without merging**
