### PR TITLE
Gem updates (Jekyll 3.1)

### LINKED ISSUE #493: Upgrade to Jekyll 3.1
- [x] Do upgrade

Couple of new features which may be of use

- [x] *Use Liquid::Drops instead of Hashes in #to_liquid*, reap the speed
- [ ] *Enhancement: include tags can now accept multiple liquid variables*, will simplify some of our includes

### PR DESCRIPTION
**Pull request by wjdp**
- Update :gem:s, inc Jekyll 3.1 will close #493
- Remove `html_filter.rb`, Can't remember what I added it for (88f5a9aee9d5a5b353babd8bdc36c4eb640677b9) it's not used anywhere and means removal of two :gem:s
- [x] Fix broken coffeescript build in Jekyll 3.1
- Migrate to using Uglify gem in rakefile rather than jekyll plugin (jekyll-jsminify)

### CODE REVIEW

**Comment by wjdp** [comment]
:red_circle: Looks like JS/coffeescript is a bit brokened

```
- ./_site/404.html
  *  internal script /js/app.js?cachebust=201601270314 does not exist (line 735)
```

**Comment by wjdp** [comment]
`/js/app.js` is present locally, I am confussled

image

**Comment by nhyty** [comment]
Any news

**Comment by wjdp** [comment]
It's brokened, I don't know why

**Comment by wjdp** [comment]
I now know why https://github.com/gjtorikian/jekyll-jsminify/issues/3

**Comment by wjdp** [comment]
Note to future me in 851a166 we changed from jekyll-jsminify to just running uglifier in the rakefile. Less dependence on a third party thing breaking for a super simple task.

**Pull request merged**
