### PR TITLE
Various August submissions

### PR DESCRIPTION
**Pull request by samozzy**

### CODE REVIEW

**Comment by BenWoodford76** [comment]
@samozzy we're getting a 403 error on Vimeo

and a href blank error in West Side Story

**Comment by samozzy** [comment]
I have no idea why either of these are occurring. Any thoughts?

**Comment by BenWoodford76** [comment]
@samozzy could the href issue be down to the use of speech marks on the special thanks sections?

**Comment by BenWoodford76** [comment]
Right, I'm unsure as to what's causing this error, any chance @wjdp could have a look? or @davidtaylorhq ??

**Comment by wjdp** [comment]
@BenWoodford76 I've dug through the source of the West Side Story page on Netlify but can't find anything. All the hrefs there seem to be fine.

**Comment by samozzy** [comment]
Is #246 coming back to haunt us?

**Comment by BenWoodford76** [comment]
will close with #1535

**Pull request closed without merging**
