### PR TITLE
Maybe now tracking incognito programme with LFS?

### PR DESCRIPTION
**Pull request by GingertronMk1**

### CODE REVIEW

**Comment by samozzy** [comment]
`Error downloading object: assets/for_shows/incognito-progamme.pdf (b23e220): Smudge error: Error downloading assets/for_shows/incognito-progamme.pdf (b23e220eeaf9ec056be22e35dfdf471c4d21371b343ea12b1572df4d0ec03c1a): batch request: missing protocol: ""`

**Comment by GingertronMk1** [comment]
So how are the other pdfs stored?

**Comment by wjdp** [comment]
Just checked master, this seems to be tracked by LFS now

image

**Comment by wjdp** [comment]
File was invalid and seems to be other issues with our asset serving domain. Made a new PR with my attempt here #1480

**Comment by wjdp** [comment]
Fixed in #1480

**Pull request closed without merging**
