### PR TITLE
Sticky breadcrumbs

### PR DESCRIPTION
**Pull request by wjdp**
Make this:

image

Do this:

image

Opening PR now to get the netlify build to do some cross browser testing.

### CODE REVIEW

**Comment by wjdp** [comment]
@newtheatre/editors Can a few of us prod this today. Assuming all is well I'll merge it in this evening,

**Comment by davidtaylorhq** [comment]
Looks very pretty - doesn't work on safari though. http://caniuse.com/#search=sticky suggests it needs a `-webkit-` prefix

**Comment by samozzy** [comment]
When hovering, the sub-levels change colour, whereas the root level does not. Should this change to provide uniformity in the same visual indicator?
Goes a bit awry with *super* long show titles. (Many many words, more than [this](https://deploy-preview-802--history-project-dev.netlify.com/years/10_11/strictly_come_stars_in_their_eyes_on_ice/)). Is it worth putting an ellipsis for show titles > x or is it too much of a fringe case?

Works really well though :D

**Comment by wjdp** [comment]
Re. Safari problems: this is why we use autoprefixer. I'll expend some effort on this soonish so we can get this merged.

**Comment by BenWoodford76** [comment]
*poke* anyone been bored enough to have a look at this yet?

**Pull request closed without merging**
