### PR TITLE
Provide playwrights with a credit

### PR DESCRIPTION
**Pull request by samozzy**
For student written shows with one listed playwright, list them in the crew list and provide them with a credit on the person page. 

Additionally add `playwright_false` as an override to suppress this, alongside `playwright_alias` for students who write under a different name (eg M Craig).

Screenshot 2021-12-21 at 10 57 41 AM
Screenshot 2021-12-21 at 10 57 53 AM
Screenshot 2021-12-21 at 10 57 59 AM

### CODE REVIEW

**Comment by BenWoodford76** [comment]
you happy for this to merge sam?

**Comment by samozzy** [comment]
Standby; Gatsby doesn't currently appear on the list despite ticking all the boxes on paper. Some troubleshooting to occur.

**Comment by samozzy** [comment]
This is good to go 🙂

**Review by BenWoodford76 — APPROVED** [review]

**Comment by BenWoodford76** [comment]
once build passes i'll merge it

**Pull request merged**
