### PR TITLE
WIP: Thewlis data

### PR DESCRIPTION
**Pull request by wjdp**
@samozzy Can these (incomplete) additions be merged?

### CODE REVIEW

**Comment by samozzy** [comment]
Yep! My bad

**Comment by nhyty** [comment]
So this is good to merge once i get it working?

**Comment by nhyty** [comment]
@davidtaylorhq or @wjdp , can u quickly make this branch work, i'm sure you could fix it quickly but it appears to be beyond me

**Comment by nhyty** [comment]
it appears to be an issue with the special characters on the playwrights page that is causing the issues

**Comment by nhyty** [comment]
fairly certain this was caused by #246

**Pull request merged**
