### PR TITLE
NNT Edfringe 2018

### PR DESCRIPTION
**Pull request by GingertronMk1**

### CODE REVIEW

**Comment by GingertronMk1** [comment]
@ntbot holy shit, two months off and I've actually done it properly

**Comment by BenWoodford76** [comment]
let me know when you're finished Jack and I'll review it :)

**Comment by GingertronMk1** [comment]
@BenWoodford76 Go for it

**Comment by BenWoodford76** [comment]
@samozzy wasn't it Olive studio or something like that?

**Comment by BenWoodford76** [comment]
Also, regarding the review, there are other shows in the archive that have particularly horrific reviews but we've included them as it shows different opinions regarding the shows we've put on, that being said if everyone else want's to omit it then I won't strongly argue the point

**Comment by nhyty** [comment]
@BenWoodford76 Beef comes to mind

**Comment by GingertronMk1** [comment]
@BenWoodford76 This is an archive, archives can contain negative things. If we omit bad reviews it becomes propaganda effectively and I certainly don't want that.

**Comment by nhyty** [comment]
@GingertronMk1 100% agree

**Pull request merged**
