### PR TITLE
Implement an 'outdated browser' banner shown to ≥ IE11

### LINKED ISSUE #1252: Add "Old browsers not supported" banner
No longer supporting IE or anything < 2 years old?

And direct to an info site about why

### PR DESCRIPTION
**Pull request by wjdp**
We don't support anything > 3 years old. IE11 was released in 2013.

Will close #1252 

image

### CODE REVIEW

**Comment by nhyty** [comment]
Did we get anywhere with this?

**Comment by wjdp** [comment]
@nhyty Not really no, I think the HTML just needs an ignore tag on the `#` link and tests should pass. Will get around to it one day if no-one else picks up.

**Comment by BenWoodford76** [comment]
@samozzy any chance you're feeling bored and want to take a look at this?

**Comment by wjdp** [comment]
Honestly I don't think this is worth the effort. Usage is so low now and the vast majority of broken sites do not show any sort of banner.

**Comment by wjdp** [comment]
This PR is horrific. If we ever want the work just cherry pick d379b96 .

**Pull request closed without merging**
