### PR TITLE
Update 'Twinss'

### PR DESCRIPTION
**Pull request by samozzy**
Did some Googling, found some info.

Also acquired a pdf of the paywalled article from The Times which has the dates. What do we want to do with this?

### CODE REVIEW

**Comment by BenWoodford76** [comment]
upload pdf?

**Comment by samozzy** [comment]
My hesitation is that we'd be providing something paid-for for free. I guess we can always take it down!

**Comment by wjdp** [comment]
If you put the times link through archive.is, it should archive it without the paywall.

**Comment by samozzy** [comment]
Magic - ta! I'll finish this off now in that case.

**Pull request merged**
