### PR TITLE
Smugmug single image support

### LINKED ISSUE #515: Enable use of SmugMug assets for show assets
As we grow our show assets the repo grows with. SmugMug is a tad easier on editors. Looking to migrate to that fully for binary assets.

Something like:

```yaml
assets:
  - type: poster
    smugmug: ABC123
  - type: flyer
    smugmug: ABC124
  - type: programme
    filename: the_pillowman_programme.pdf
    title: Programme
```

PDFs don't live on SmugMug so stay as they are.

We won't be adding SCANFEST assets to repo, they shall wait for this feature.

### LINKED ISSUE #516: Enable use of SmugMug for people headshots
Similar to #515, for headshots too.

As we only have 3 with headshots so far I shall make this as a breaking change.

### LINKED ISSUE #519: Person headshot mangled on mob-land
Goes weird on mobile, will only has half a face.

image

### PR DESCRIPTION
**Pull request by wjdp**
Hosting of single images on SM for use as headshots, show assets and venue photographs.

- [x] Use SmugMug for people headshots. ID lookup tool available here: https://history.newtheatre.org.uk/util/smug-headshots/. Will close #516.
- [x] Use SmugMug for show image assets (posters, programmes etc). ID lookup tool available here: https://history.newtheatre.org.uk/util/smug-show-assets/. Will close #515.
- [x] Cache single image API fetches.
- [x] As a fun coincidence this will fix #519 as SM does cropping for us. We can get rid of the JS that auto centres non square images.
- [x] Update docs

### CODE REVIEW

**Comment by wjdp** [comment]
@nhyty get in mah branch! All instances of `image: xyz.jpg` in show files need changing to SmugMug image IDs from https://history.newtheatre.org.uk/util/smug-show-assets/.

Anyone else, help would be appreciated. There's quite a few...

image

**Comment by nhyty** [comment]
I'll deal with those at some point soon :)

**Comment by wjdp** [comment]
Never mind :)

**Comment by nhyty** [comment]
I'm glad!

**Pull request merged**
