### PR TITLE
Vagrant

### PR DESCRIPTION
**Pull request by tomtom5152**
Add a vagrant environment to make it easy to develop on all platforms, including windows (shudder).

Currently configured to just create the ruby env and install deps, but could also add automated builds when files are changed and automated testing on a new build. I feel this is outside the scope of this PR and could be done at a future date.

### CODE REVIEW

**Comment by wjdp** [comment]
Gah, character encoding broke

```
Rendering site... 
  Conversion error: Jekyll::Converters::Sass encountered an error while converting 'css/main.sass':
                    Invalid US-ASCII character "\xE2" on line 8
```

**Comment by tomtom5152** [comment]
It was earlier, thats very unusual. I don't think this is likely to be an issue with the vagrant box more probably either the build script or the sass file itself (why the hell is there non ASCII in a sass file?)

**Comment by wjdp** [comment]
Not sure where it is, all files get imported my `main.sass` and really helpfully the error gets thrown there. It should be using UTF-8 and therefore no problem and is what is happening locally.

**Comment by tomtom5152** [comment]
I did have a sass issue with (lib/octicons) just not getting downloaded due to the directory already existing, thought I had fixed that and it does sound unrelated.

**Comment by wjdp** [comment]
Was an issue with having deps in VC a while ago, think there are a few bits that still stuck around.

**Pull request merged**
