### PR TITLE
Ghetto SmugMug Bug

### PR DESCRIPTION
**Pull request by wjdp**
The bug in the smug mug. #246 

Affects ghetto, king lear and cheque as they have single items in their SM albums.

### CODE REVIEW

**Comment by wjdp** [comment]
Smug's not very happy about his bug

smb

**Comment by nhyty** [comment]
Any idea on what is causing this?

**Comment by wjdp** [comment]
Incorrectly interpreting API responses when they're an album of a single item is my best guess (see the issue).

As this only affects a small number of shows, which have had their album's removed, it's rather low priority.

**Comment by wjdp** [comment]
Also I've done a history rewrite to get rid of some big binaries so this and a few other PRs are rather broken

**Comment by nhyty** [comment]
Can this go away due to #556

**Comment by wjdp** [comment]
Nah, this is a SmugAlbum thing, will get round to it soon

**Comment by wjdp** [comment]
Branch was diverged, will return to this later

**Pull request closed without merging**
