### PR TITLE
Adding information from emails to history@

### PR DESCRIPTION
**Pull request by BenWoodford76**
See commits for descriptions

### CODE REVIEW

**Comment by samozzy** [comment]
@BenWoodford76 Can you set `person: false` on some of the photographers?

**Comment by BenWoodford76** [comment]
@samozzy  do you know which photographers?

**Comment by wjdp** [comment]
@BenWoodford76 Based on who has a person page already these are unpersons:

- Daniel Cresswell
- Alexander Berman
- Kah Lok

Unknown: Josh Spear (maybe, see https://history.newtheatre.org.uk/people/josh_spear/, has only ever been a photographer)

**Comment by samozzy** [comment]
Correction: [Daniel Cresswell](https://history.newtheatre.org.uk/people/dan_cresswell/) is already a person (under Dan)

**Review by samozzy — APPROVED** [review]

**Pull request merged**
