### PR TITLE
Refactor/show link list

### LINKED ISSUE #842: Add show links to link register
The [link register](https://history.newtheatre.org.uk/util/link-register/) is missing links from shows. Must have not gotten around to that! Fix.

### PR DESCRIPTION
**Pull request by wjdp**
- Switch show link list to use the LinkList plugin, was just passing through raw. Will close #842.
- Add better error handling to link lists. Now complains with good messages including document filename when missing `type`, `href`/`username` and publisher when Article / Review.

### CODE REVIEW

**Comment by wjdp** [comment]
Ignore the codeclimate check. We want to keep tabs on TODOs, but shouldn't disallow adding them.

**Comment by wjdp** [comment]
:red: Missing some icons:

image

**Comment by wjdp** [comment]
*Reviewers:* Have a gander over the changes, but mainly check the branch site for any issues with rendering links.

**Comment by nhyty** [comment]
Can't find any issues while looking around.

**Pull request merged**
