### PR TITLE
Create skeleton.md

### PR DESCRIPTION
**Pull request by GingertronMk1**
A skeleton file (if one exists soz but I couldn't find it) to make it easier for new contributors to add shows via pull requests

Also if this isn't the right place to put it please advise

### CODE REVIEW

**Comment by GingertronMk1** [comment]
Oh yeah, additionally please add metadata it's missing, this is just the 5KOS one with all the actual data removed

**Comment by wjdp** [comment]
@GingertronMk1 It's taken three years before someone thought to do this... Well done!

**Comment by samozzy** [comment]
Renamed the file and added another for people. This is now ready for merging.
I have added this to the docs but it won't build as it links to the files being in master :sweat_smile:

**Comment by BenWoodford76** [comment]
@samozzy @nhyty could you have a look and check if there's anything missing before I merge

**Comment by GingertronMk1** [comment]
Can someone review this so it can get merged please? Season's starting and I wanna use it

**Pull request merged**
