### PR TITLE
Spring 2020

### PR DESCRIPTION
**Pull request by samozzy**
Shows to be added:
- [ ] Postgrads (I have a programme)
- [ ] Improv
- [ ] Pilgrimage
- [ ] Kiss My Neck
- [ ] La Casa
Any more?

### CODE REVIEW

**Comment by samozzy** [comment]
@GingertronMk1 / @BenWoodford76 - can either of you sort programmes via LFS? Let me know if not and I'll see if I can actually wrangle it to install on my computer!

**Comment by BenWoodford76** [comment]
@samozzy Will look later :)

**Comment by BenWoodford76** [comment]
@samozzy which shows need their programmes adding??

**Comment by samozzy** [comment]
All My Sons, Celebration and Deadmeat for now. I think there are more but @skylarth hasn't got them yet.

**Comment by samozzy** [comment]
Right I don't have the postgrads programme with me (it's in Nottingham). @skylarth - is that all the shows other than that?

**Comment by BenWoodford76** [comment]
any idea why Travis now appears to be not completing builds?

**Comment by BenWoodford76** [comment]
Netlify looks good so i'm gonna assume that travis is happy....

**Comment by samozzy** [comment]
Yeah it's [passed](https://travis-ci.org/github/newtheatre/history-project/builds/666562995) just not told GitHub...

**Pull request merged**
