### PR TITLE
Added Ian's IMDb page

### PR DESCRIPTION
**Pull request by GingertronMk1**

### CODE REVIEW

**Comment by BenWoodford76** [comment]
@wjdp can the links field do IMDB?

**Comment by BenWoodford76** [comment]
I 'think' the build fail is to do with the IMDB link

**Comment by samozzy** [comment]
@BenWoodford76 Given it's the only thing that's changed, I would hope so 😜  Need to wrap the href in quotes.

**Comment by BenWoodford76** [comment]
@samozzy I think it's also down as the wrong type??

**Comment by samozzy** [comment]
Yeah, should be just `IMDb`

**Comment by GingertronMk1** [comment]
am I gonna have to change this?

**Comment by nhyty** [comment]
@GingertronMk1 I'll fix it later

**Comment by wjdp** [comment]
:wave: Welcome @GingertronMk1!

**Pull request merged**
